version: 2
jobs:
 build:
   working_directory: ~/edx-platform
   machine:
      enabled: true
      image: ubuntu-1604:201903-01

   parallelism: 4

   steps:
     - checkout

     # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
     # CircleCI 2.0 does not support environment variables that refer to each other the same way as 1.0 did.
     - run:
         name: Creating directories and files
         command: |
           mkdir -p ~/python_3.5.2 ~/sqlite_3.14
           mkdir -p circleci-test-results/artifacts/junit circleci-test-results/artifacts/test_root/log
           sudo mkdir -p /data/db
           sudo chown -R $USER:$USER /data/db
           sudo chmod 0755 /data/db/

     - run:
         name: Installing sqlite3 v3.14.1
         command: |
           cd ~/sqlite_3.14
           wget https://s3.amazonaws.com/vagrant.testeng.edx.org/libsqlite3-0_3.14.1-1build1_amd64.deb
           sudo dpkg -i libsqlite3-0_3.14.1-1build1_amd64.deb
           sudo apt-get -f -y install

     - run:
         name: Installing Python v3.5.2
         command: |
           cd ~/python_3.5.2
           wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz
           tar -xvf Python-3.5.2.tgz
           cd Python-3.5.2
           ./configure
           sudo make install
           pyenv global 3.5.2

     - run:
         name: Installing and creating virtual environment
         command: |
           sudo pip3 install virtualenv
           rm -rf ~/virtualenvs/
           virtualenv --python=`which python3.5` --no-wheel --no-setuptools ~/virtualenvs/venv-3.5.2
           source ~/virtualenvs/venv-3.5.2/bin/activate
           cd && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
           python get-pip.py pip==20.0.2 wheel==0.35.1 setuptools==50.3.0

     - run:
         name: Installing Node v12.18.4 and Node packages
         command: |
           curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
           sudo apt-get install -y nodejs
           sudo npm install -g n
           sudo n 12.18.4

     - run:
         name: Installing pre-reqs
         command: |
            source ~/virtualenvs/venv-3.5.2/bin/activate
            bash ./scripts/install-system-req.sh
            sudo locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            export LANGUAGE=en_US:en
            export LC_ALL=en_US.UTF-8
            sudo service mongod start

     - restore_cache:
              name: Restores cache if any of the requirements file have not changed since the previous run
              key: >-
                virtual-environment-cache-v9
                -{{ checksum "requirements/edx/development.txt" }}
                -{{ checksum "requirements/edx/custom.txt" }}

     - restore_cache:
         name: Restores cache if the package.json file have not changed since the previous run
         key: virtual-environment-cache-v9-{{ checksum "package.json" }}

     # Mirror what paver install_prereqs does.
     # After a successful build, CircleCI will
     # cache the virtualenv at that state, so that
     # the next build will not need to install them
     # from scratch again.
     # We need to pin djangorestframework until we have upgraded to edxval 0.0.19 or greater.
     # Output the installed python packages to the console to help with troubleshooting any issues
     # with python requirements.

     # NOTE: If coveralls or django-rest-framework version is changed below, update/increment the
     # cache version as well under 'restore_cache' and 'save_cache' commands
     # i.e virtual-environment-cache-v{x} => virtual-environment-cache-v{x+1}
     - run:
         name: Installing requirements
         command: |
           source ~/virtualenvs/venv-3.5.2/bin/activate
           npm install
           pip install google-compute-engine
           pip install --exists-action w -r requirements/edx/development.txt
           pip install --exists-action w -r requirements/edx/custom.txt
           pip install coveralls==1.0
           pip freeze

     - save_cache:
         key: >-
           virtual-environment-cache-v9
           -{{ checksum "requirements/edx/development.txt" }}
           -{{ checksum "requirements/edx/custom.txt" }}

         paths:
            - ~/virtualenvs/venv-3.5.2

     - save_cache:
         key: virtual-environment-cache-v9-{{ checksum "package.json" }}
         paths:
            - node_modules

      # Run tests for the system.
      # all-tests.sh is the entry point for determining
      # which tests to run.
      # See the circleCI documentation regarding parallelism
      # to understand how multiple containers can be used to
      # run subsets of tests in parallel.
      # if a command runs 900 seconds without output, kill it
     - run:
         name: Running Tests
         command: |
           source ~/virtualenvs/venv-3.5.2/bin/activate
           ./scripts/all-tests.sh
         no_output_timeout: 15m

     # If you have enabled coveralls for your repo, configure your COVERALLS_REPO_TOKEN
     # as an Environment Variable in the Project Settings on CircleCI, and coverage
     # data will automatically be sent to coveralls. See https://coveralls.io/
     # If you have not set up set up coveralls then the following statement will
     # print a message but not affect the pass/fail status of the build.
     - run:
         name: Generate report
         command: |
           source ~/virtualenvs/venv-3.5.2/bin/activate
           if [ $(find reports -type f | wc -l) -gt 0 ]; then cp -r reports/. circleci-test-results/artifacts/junit; fi
           if [ -z $COVERALLS_REPO_TOKEN ]; then echo "Coveralls token not defined."; else coveralls; fi

     - store_artifacts:
         path: circleci-test-results/artifacts/junit

     - store_artifacts:
         path: test_root/log
         destination: log

     - store_test_results:
         path: circleci-test-results/artifacts/junit
